### ISSUE TITLE
Should install repo on the user's behalf

### ISSUE THREAD

**Issue by faddat** [AndroGeek974/AndroidAutoCompiler#2]
Welcome on ACC 1.0_061115

You need to launch this program where you want to see your sources.

Folder name for the sources : 
sources

That's good, now just wait, we're gonna download things you need to build.
[sudo] password for faddat: 
sudo: apt-add-repository: command not found
Okay, java is ready to work !
sudo: apt-get: command not found
Done !
Okay, you have to tell wich sources you want to build.

1.CyanogenMod
2.AOSP
3.AOKP
4.Paraoid Android
5.OmniROM
2
So, you chose AOSP but wich version ?

1.Android 5.1.1
2.Android 6.0.0
2
sh: repo: command not found
Traceback (most recent call last):
  File "aac.py", line 70, in <module>
    if choice == 4 :
NameError: name 'choice' is not defined
faddat@manjaor ~/AndroidAutoCompiler> python aac.py

Welcome on ACC 1.0_061115

You need to launch this program where you want to see your sources.

Folder name for the sources : 
cyanogenmod

That's good, now just wait, we're gonna download things you need to build.
sudo: apt-add-repository: command not found
Okay, java is ready to work !
sudo: apt-get: command not found
Done !
Okay, you have to tell wich sources you want to build.

1.CyanogenMod
2.AOSP
3.AOKP
4.Paraoid Android
5.OmniROM
1
So, you chose CyanogenMod, but wich branch ?

1.CM-12.0
2.CM-12.1
3.CM-13.0 (Not ready at all)
2
sh: repo: command not found
Traceback (most recent call last):
  File "aac.py", line 70, in <module>
    if choice == 4 :
NameError: name 'choice' is not defined
faddat@manjaor ~/AndroidAutoCompiler>

**Comment by msfjarvis** [comment]
OK @faddat , I get the repo issue. But why isn't apt-get working??? Are you using Debian or Ubuntu coz apt is Debian's package manager. Fedora has yum, Arch Linux has pacman and so on.

Also remember to use python3, rather than python which you used above.

**Comment by msfjarvis** [comment]
@faddat, i've fixed this issue in my branch and added the commit to the pull request. I suggest you use my branch going forward since the original has gone stale.

**Comment by faddat** [comment]
Sure thing.  I'll do that.  Also, I think that what I've got going on in
superordinate/cyanogenbuild is worth a look-- but how would one gui-ify a
bash script?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by msfjarvis** [comment]
Easy.  Throw in the bash commands in os.system in python

**Comment by faddat** [comment]
That will let us gui-ify?  You got an hour beginning in 20 minutes to hash
this out?

**Comment by msfjarvis** [comment]
This would work in the same way as it does in @AndroGeek974's AAC scripts. I'll take a look at the thing and tell you what can we do

**Comment by DamienBoyer974** [comment]
Maybe you guys can take a look at GUI version. The main problem now is to resolve the frames problem, after that, we'll add more stuffs and design it

**Comment by msfjarvis** [comment]
Cool @AndroGeek974, I've taken a look. I think it is a nice idea to ask the things that we want through tkinter.messagebox popups. But I can't seem to find a way to customise it. It only accepts questions defined already. You can have a OK-Cancel question and yes-no but not input type.

**Comment by DamienBoyer974** [comment]
I tried popups, using new Tk() for wich sections but that was simply horrible to user experience. I think I'm going to restart the project at zero and use a Tk frame template to integrate AAC properly.

Huh, @MSF-Jarvis, what about AAC logo ? You tried something ?

**Comment by msfjarvis** [comment]
Sorry dude, had a my hands full with something. But I'll try and get someone to design it, I'm not a designer after all...

**Comment by DamienBoyer974** [comment]
Ok, that's not important for now

**Comment by msfjarvis** [comment]
Yeah, we need to get it working first.

**Comment by DamienBoyer974** [comment]
Does it work for you with you lastest modifications ?

**Comment by DamienBoyer974** [comment]
Check AndroGeek974/AndroidAutoCompiler, I've found a temporary "fix" to managing frames using start.sh

**Comment by faddat** [comment]
In my mind the thing we need to do is define what we're doing, then do
it..... ya know?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421
